[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "interval-pca"
version = "0.2.2"
description = "Interval algebra and Interval Principal Component Analysis (IPCA), following Gioia & Lauro (2006)"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy>=1.20",
    "scipy>=1.7",
    "matplotlib>=3.3"
]

authors = [
  { name = "Apostolos Tapsas", email = "apotapsas@gmail.com" }
]

license = {text = "MIT"}

[project.optional-dependencies]
test = ["pytest>=7.0"]

[tool.setuptools]
packages = ["interval_pca"]
